### ISSUE TITLE
That "Powered by Fue" part on screen is weird and unnecessary. 

### ISSUE THREAD

**Issue by NomanBaigA** [moha-b/Flappy-Bird#23]
**Describe the bug**
-- That part is not good for user experience I never see this thing on the main game screen.

**To Reproduce**
I tried to remove it but the space between barriers is becoming wide.

-- Tested on Android 9 device.

**Comment by moha-b** [comment]
Sure, any UI enhancement is always welcome. If you have more suggestions, I would be happy to hear them. I will edit it as soon as possible.

**Comment by NomanBaigA** [comment]
> Sure, any UI enhancement is always welcome. If you have more suggestions, I would be happy to hear them. I will edit it as soon as possible.

Sure, I will let you know.

**Comment by moha-b** [comment]
u can reopen it once you have a new design
